### ISSUE TITLE
 Cannot download weights

### ISSUE THREAD

**Issue by davidpob99** [chumingqian/Model_Compression_For_YOLOV4#11]
Hi,

Can someone upload the yolov3 pytorch weights again to Google Drive? The link stored in the code (https://drive.google.com/drive/folders/1uxgUBemJVw9wZsdpboYbzUN4bcRhsuAI) does not work anymore.

https://github.com/chumingqian/Model_Compression_For_YOLOV3-V4/blob/c0fed1842a5f2bf35c102bb3188230b547c248c0/weights/download_yolov3_weights.sh#L12

Thanks in advance

**Comment by chumingqian** [comment]
Hi, david:
    Will  you  try  this: https://pan.baidu.com/share/init?surl=JZylwRQIgAd389oWUu0djg ; 
    Extract code：k8ms;
