### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by dagezhuang** [chumingqian/Model_Compression_For_YOLOV4#13]
您好！在训练dior数据集，命令如下：python3 train.py --data data/dior.data --batch-size 1 --weights weights/yolov3-608.weights -pt --cfg cfg/yolov3/yolov3-onDIOR.cfg --img-size 608 --epochs 5 --device 0         
但是显示报错，                                              
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex                                                              
Namespace(AT_str=-1, BN_Fold=False, FPGA=False, KDstr=-1, a_bit=8, adam=False, batch_size=1, bucket='', cache_images=False, cfg='./cfg/yolov3/yolo
v3-onDIOR.cfg', data='data/dior.data', device='0', ema=False, epochs=5, evolve=False, img_size=[608], multi_scale=False, name='', nosave=False, no
test=False, prune=-1, pt=True, quantized=0, rect=False, resume=False, s=0.001, single_cls=False, sr=False, t_cfg='', t_weights='', w_bit=8, weight
s='weights/yolov3-608.weights')
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA GeForce RTX 3090', total_memory=24259MB)

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
WARNING: smart bias initialization failure.
WARNING: smart bias initialization failure.
WARNING: smart bias initialization failure.
Model Summary: 222 layers, 6.1626e+07 parameters, 6.1626e+07 gradients
Optimizer groups: 75 .bias, 75 Conv2d.weight, 72 other
<.....................using fencemask.......................>
Caching labels (11725 found, 0 missing, 0 empty, 1 duplicate, for 11725 images): 100%|███████████████████| 11725/11725 [00:01<00:00, 10361.64it/s]
single-gpu sparse
Caching labels (11738 found, 0 missing, 0 empty, 0 duplicate, for 11738 images): 100%|████████████████████| 11738/11738 [00:01<00:00, 9748.10it/s]
Image sizes 608 - 608 train, 608 test
Using 0 dataloader workers
Starting training for 5 epochs...
learning rate lr: 0.000100

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                                                                                   | 0/11725 [00:00<?, ?it/s]
Traceback (most recent call last):
File "train.py", line 716, in <module>
    train(hyp)  # train normally
  File "train.py", line 360, in train
    loss, loss_items = compute_loss(pred, targets, model)
  File "/home/ubuntu/Model_Compression_For_YOLOV3-V4/utils/utils.py", line 390, in compute_loss
    tcls, tbox, indices, anchor_vec = build_targets(p, targets, model)
  File "/home/ubuntu/Model_Compression_For_YOLOV3-V4/utils/utils.py", line 1371, in build_targets
    t, a = t[j], a[j]
TypeError: 'builtin_function_or_method' object is not subscriptable

定位到def build_targets(p, targets, model)函数，对应t和j的输出为：
tensor([[ 0.00000,  5.00000,  8.20687,  0.94250,  7.33875,  1.88500],
        [ 0.00000,  5.00000,  2.86250, 17.80500,  5.72500,  2.39000],
        [ 0.00000,  5.00000,  8.20687,  0.94250,  7.33875,  1.88500],
        [ 0.00000,  5.00000,  2.86250, 17.80500,  5.72500,  2.39000],
        [ 0.00000,  5.00000,  8.20687,  0.94250,  7.33875,  1.88500],
        [ 0.00000,  5.00000,  2.86250, 17.80500,  5.72500,  2.39000]], device='cuda:0')
tensor([False, False,  True,  True,  True,  True], device='cuda:0')

请问如何解决？

**Comment by chumingqian** [comment]
hi, there:

The `TypeError` suggests you're trying to index a function or method instead of a list or tensor. It seems `t` or `a` is not what you expect.

To fix this:

1. **Check Initialization**: Ensure `t` and `a` are initialized as tensors or lists, not functions or methods.

2. **Print Debug Info**: Add print statements to verify the types of `t` and `a` before the line causing the error.

3. **Correct Code**: Confirm you're indexing the correct variables.

Here's a sample check:

```python
print(type(t), type(a))  # Ensure these are tensors or lists
print(t, a)              # Check their values

t, a = t[j], a[j]        # Ensure j is a valid index or boolean mask
```

Ensure `t` and `a` are not overwritten by functions or methods earlier in the code.
