### ISSUE TITLE
Cannot download weights

### ISSUE THREAD

**Issue by walzimmer** [chumingqian/Model_Compression_For_YOLOV4#2]
Hi,

can someone please upload the YoloV4 weights trained on VisDrone2020 on Google Drive or wetransfer.com?

These one can only be downloaded from China:

https://pan.baidu.com/s/1zOFyt_AFiNk0fAFa8yE9RQ
Extract code：xblu

Best regards,
Walter

**Comment by chumingqian** [comment]
Hi @walzimmer :
  Here  is the link https://drive.google.com/file/d/1dQDjCoGKPWeRz7z-0TJI8fAeKMx13JYi/view?usp=sharing  ,you can try this

**Comment by walzimmer** [comment]
Unfortunately the model does not detect vans using these weights. On what classes have you trained the network on for how long (num. of epochs)?

**Comment by davidpob99** [comment]
The download Google Drive link is down
